name: svelte-builder

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  svelte-builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: svelte-builder-step
        uses: ./.github/actions/svelte-builder
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
